---
#
# Installing Auditbeat
#

# Add Elasticsearch apt key

- name: Add Elasticsearch apt key
  apt_key:
   url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
   state: present

# Add the Elasticsearch apt repo

- name: Adding Elasticsearch repo
  apt_repository:
   repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
   state: present
   update_cache: yes

# Install transport-https

- name: Install transport-https
  apt:
   name: apt-transport-https
   state: present


# Install Auditbeat 

- name: Install Auditbeat with apt
  apt:
   name: auditbeat
   state: present

# Copy template config Auditbeat 

- name: Copy file configuration
  template:
    src: auditbeat.j2
    dest: /etc/auditbeat/auditbeat.yml
    owner: root
    group: root
    mode: '0600'
  notify:
    - restart auditbeat

# Starting Service Auditbeat 

- name: Starting auditbeat 
  service:
   name: auditbeat 
   state: started
   enabled: true

